class Context:
    def set_memory_limit(self, limit: int) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def set_time_limit(self, limit: float) -> None: ...
    def eval(self, source: str) -> object: ...
