from collections.abc import Iterable

class YAMLError(Exception): ...
class _AliasToken: ...

class _Tokens:
    AliasToken: type[_AliasToken]

tokens: _Tokens

def scan(stream: str) -> Iterable[object]: ...
def safe_load(stream: str) -> object: ...
